<?php
	$title = 'Delete member';
	$url   = $this->url('member', ['action' => 'delete', 'id' => $id]);

	$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>

<p>
    Are you sure that you want to delete
    "<?= $this->escapeHtml($member->f_name.' '.$member->f_name) ?>" by
    "<?= $this->escapeHtml($member->address) ?>"?
</p>

<form action="<?= $url ?>" method="post">
	<div class="form-group">
	    <input type="hidden" name="id" value="<?= (int) $member->id ?>" />
	    <input type="submit" class="btn btn-danger" name="del" value="Yes" />
	    <input type="submit" class="btn btn-success" name="del" value="No" />
	</div>
</form>